### ISSUE TITLE
Reporting replication errors: display long status?

### ISSUE THREAD

**Issue by jh23453** [peterpakos/ipa_check_consistency#33]
Right now I do have replication errors and see this:

```
Replication Status  freeipa2 18 freeipa1 0       
```
With ldapsearch I get:
```
nsds5replicaLastUpdateStatus: Error (18) Replication error acquiring replica: Incremental update transient error.  Backing off, will retry update later. (transient error)
```
An easy way to see the long text might be helpful.
May be something like this (only for status <> 0):
```
Replication Status  freeipa2 18 freeipa1 xx       
Status 18: Replication error acquiring replica...
Status xx: text for status
```

**Comment by peterpakos** [comment]
This behaviour is by design.

The numbers `18` and `0` are the actual update status codes from replicas. They are the same status codes as we can see in the output of ``ipa-replica-manage list -v `hostname` ``:
```
ipa01.example.com: replica
...
  last update status: 0 Replica acquired successfully: Incremental update succeeded
...
ipa02.example.com: replica
...
  last update status: 0 Replica acquired successfully: Incremental update succeeded
...
```

An easy way to see the long text is to simply run ``ipa-replica-manage list -v `hostname` ``.

Some customers have dozens of FreeIPA replicas that they wish to monitor, I don't think it would be a good idea to cram the output with full status message from each replica.
